### ISSUE TITLE
White screen on startup

### ISSUE THREAD

**Issue by tobloef** [dixonary/draft-reMarkable#12]
I've installed draft on my reMarkable running version 2.0.2.0 and whenever I turn on the device, all I see is a white screen. I'm still able to press the buttons in the launcher, I can even see a faint outline of them because the display haven't done a full update, and everything works fine if I use button-capture-reMarkable to exit xochitl, but on the initial boot, the launcher is completely blank.

Let me know if I can provide anything to help solving this problem. Thanks!

**Comment by dixonary** [comment]
Apologies, I didn't even see this issue pop up. I believe this is closed by #14 but please let me know if there are any further issues!
