### ISSUE TITLE
More detailed installation instructions

### ISSUE THREAD

**Issue by Qqwy** [dixonary/draft-reMarkable#3]
Hello! I'm not new to compiling software, but I am new to QtCreator, and how to set it up for sending software to the reMarkable.

More detailed instructions would be greatly appreciated!

**Comment by dixonary** [comment]
Hey - that would definitely be a good thing to add.

I'm terrifically busy with work at the moment. I know there are a number of people who regularly use `draft` and `QtCreator` other than me. If you can find any of them by name (for example, on the /r/RemarkableTablet subreddit) then please invite them to update the Readme with more detailed instructions.

Otherwise I will have to get round to it once I'm slightly less busy, which is looking to be mid-September at the earliest. 🙂

**Comment by Qqwy** [comment]
No worries! I'm already very grateful that you were able to find the time to post above message. I know how it is to have a busy worklife :sweat_smile:.

I'll ask around on the Subreddit. If I get some concrete information, I'll probably send a Pull Request your way :wink: .

**Comment by dixonary** [comment]
Best of luck!

**Comment by Evidlo** [comment]
It would be nice if there were releases, so users don't have to download the toolchain and configure qtcreator themselves.

**Comment by dixonary** [comment]
Agreed! If anyone would like to compile the program to a release candidate (especially if they could provide a simple `scp` based install script!) I would be happy to bring them in.

**Comment by jtraulle** [comment]
Also interested by this to use plato aside of Xocitl but will wait until someone find the time to propose more detailed install instructions as I do not want to brick my tablet :P

**Comment by dixonary** [comment]
Seconding that some more instructions, or a compiled binary, would still be great. Sorry that I don't have time to do it myself!

Worth noting that I tried Plato and didn't get very far. There are, or *were*, some features that didn't seem to work. So I wouldn't worry too much! But if you want to try it yourself , you can just run Plato directly on the rM without draft.

**Comment by jtraulle** [comment]
Thanks for the tip, just tested plato directly. Yup, not everything works but wooooh it is blazing fast to render pages compared to xochitl :heart_eyes:

**Comment by dixonary** [comment]
Indeed! Also so long as you don't actually _delete_ any existing files, and do not disable the SSH service (obviously), there's almost no chance of bricking your device. If you have successfully run Plato on it them you're most of the way there.

**Comment by flavio-rossetti** [comment]
I wrote down a brief guide on Reddit: [here](https://www.reddit.com/r/RemarkableTablet/comments/bkbps9/how_to_install_plato_reader_and_add_it_to_draft/).
It contains the steps I followed to run Plato and add it to Draft. Hope it helps!

**Comment by dixonary** [comment]
Thank you for sharing! I will put a link to this information in the README and close this issue for now.

**Comment by Evidlo** [comment]
How about a prepackaged build?  It would save people a lot of effort.

**Comment by dixonary** [comment]
I haven't rebuilt it since the last time the rM system partition was wiped so I don't think that I have any lying around. And changing computers means that I don't currently have the build workflow in place to do it quickly.

Next time I build Draft I will share the binaries 🙂

**Comment by Evidlo** [comment]
Here's my build if you want to trust it.

[draft.zip](https://github.com/dixonary/draft-reMarkable/files/3182176/draft.zip)
