### ISSUE TITLE
Error running draft project on qtcreator

### ISSUE THREAD

**Issue by LuRsT** [dixonary/draft-reMarkable#7]
This is how to reproduce:

- Installed `qtcreator` in arch linux (version 4.9.3)
- Git clone this repo
- Open file pointing to `draft.pro`
- Project gets loaded, I click on the green arrow on the left bottom side
- This error shows up:

![2019-07-31-063621_1607x128_scrot](https://user-images.githubusercontent.com/263583/62186405-1741d980-b35e-11e9-8c2e-8ee0aa15c9df.png)

**Comment by dixonary** [comment]
That's very interesting. I haven't updated the code since last running it. 

It's possible you are using a different compiler? By following the steps [here](https://remarkablewiki.com/devel/qt_creator#configuring_qt_creator) you should have a specific GCC version installed, I think.

**Comment by dixonary** [comment]
It seems like people are generally getting on OK with qtcreator and draft at the moment, so I'm going to close this one off. If this is an error then let me know!
